// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' }
import * as $0 from './routes/_404.tsx'
import * as $1 from './routes/api/blog/latest.ts'
import * as $2 from './routes/blog/[slug].tsx'
import * as $3 from './routes/blog/index.tsx'
import * as $4 from './routes/contacto.tsx'
import * as $5 from './routes/index.tsx'
import * as $6 from './routes/projects/[id].tsx'
import * as $7 from './routes/sitemap.xml.ts'
import * as $8 from './routes/sobre-mi.tsx'
import * as $9 from './routes/videos/index.tsx'
import * as $$0 from './islands/CopyButton.tsx'
import * as $$1 from './islands/PostNavigations.tsx'
import * as $$2 from './islands/ScrollToTop.tsx'
import * as $$3 from './islands/ShareModal.tsx'

const manifest = {
  routes: {
    './routes/_404.tsx': $0,
    './routes/api/blog/latest.ts': $1,
    './routes/blog/[slug].tsx': $2,
    './routes/blog/index.tsx': $3,
    './routes/contacto.tsx': $4,
    './routes/index.tsx': $5,
    './routes/projects/[id].tsx': $6,
    './routes/sitemap.xml.ts': $7,
    './routes/sobre-mi.tsx': $8,
    './routes/videos/index.tsx': $9,
  },
  islands: {
    './islands/CopyButton.tsx': $$0,
    './islands/PostNavigations.tsx': $$1,
    './islands/ScrollToTop.tsx': $$2,
    './islands/ShareModal.tsx': $$3,
  },
  baseUrl: import.meta.url,
  config,
}

export default manifest
